# Generated by Django 4.2 on 2023-04-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conditions',
            new_name='terms_conditions',
        ),
    ]
