# Generated by Django 4.2 on 2023-07-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('account', '0003_rename_user_appuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppUser',
            new_name='User',
        ),
    ]
